### ISSUE TITLE
Backdate a log

### ISSUE THREAD

**Issue by aleksandar-todorovic** [open-nomie/nomie#107]
I have collected a bunch of data points from various sources. I've just tried using Nomie. As far as I can tell, I can only fill out tracker values at the moment. I can't, for example, tell it how much I've slept yesterday or a week ago.

Could this be changed? I don't see myself constantly checking it, more like visiting it every few days and filling out the missing details.

**Comment by brandoncorbin** [comment]
In Nomie 5, click the ••• in the What's up field, in nomie 4, click the clock icon. 

![image](https://user-images.githubusercontent.com/195692/81502138-2b7e1400-92aa-11ea-866e-23ef888043e3.png)
