### ISSUE TITLE
Enable 'Save on Tap' for Number input tracker

### ISSUE THREAD

**Issue by sanderboom** [open-nomie/nomie#108]
First of all: great software! I was looking into creating something simple for one-tap-logging myself, but Nomie ticks almost all boxes plus more and +1 for the focus on privacy :ok_hand: 

Secondly: would it be possible to have a number input tracker, but still use `Save on Tap`? Only ofcourse when a default value is set. As single-tap-logging is the main feature (for me) this would be an highly appreciated addition.

Off topic question: did you elaborate somewhere (blog/podcast) on the move from Ionic to React Native? I'd be interested in your reasons. 

TIA.

**Comment by brandoncorbin** [comment]
Hey Sanderboom!  I'm going to list this as a bug - and will get it into 5.2

I'm sure I've talked about them over the years but nothing in terms of the whole journey from vanilla JS/FIrebase -> Ionic 1/Angular 1 -> Ionic 2/Angular 2 -> React Native -> Svelte JS

I'll add it to my list of posts I need to write.

**Comment by sanderboom** [comment]
Hey Mr. Corbin! Thanks for taking a look at this :rocket: 

> JS/FIrebase -> Ionic 1/Angular 1 -> Ionic 2/Angular 2 -> React Native -> Svelte JS

Collect 'em all :wink: Seems like you should have a fairly good helicopter view on pros and cons of each of these options. Do you consider Svelte in the end the best fit for Nomie or more or less the last step in Nomie as a "learning project"? Cheers.

**Comment by sanderboom** [comment]
Am I right that this does not work yet in `5.2.1`? No rush, just checking :wink:

**Comment by brandoncorbin** [comment]
> Am I right that this does not work yet in `5.2.1`? No rush, just checking 😉

Not specifically for Numeric inputs, BUT, I did fix the Single Tap Tracker not including a default value if one is set. Does that solve the use case if you switch it to a single tap?

**Comment by sanderboom** [comment]
You are right that switching the tracker to Single Tap now saves the default value. Use case check :heavy_check_mark: Cheers!
