### ISSUE TITLE
Offline Capability

### ISSUE THREAD

**Issue by thejeshgn** [open-nomie/nomie#11]
On Android (I use Firefox). I created a short cut for the home screen. It works. But if I am offline and try to launch the web app, it won't open. Since most of the content here is static. I think its a great idea to have it collect data from user offline. It can sync when it goes online.

**Comment by brandoncorbin** [comment]
Offline supports gonna be a ways out.

First we will need to get the modules/storage to be more flexible (per your other submission), get a service worker working to cache all js and css, and then get all externally called resources (Blockstack, leaflet) loading from imports and not script tags. Importing Blockstack into Svelte hasn’t been successful so far. 

Once that’s done, we will need to build a method to queue up new logs and edits for online storage engines, and save them once we’re back online.

**Comment by brandoncorbin** [comment]
So offline when using Local storage is good.. Making it work with Blockstack offline isn't a possibility anytime soon.
