### ISSUE TITLE
Invalid api_key while doing a POST on https://nomieapi.com/log

### ISSUE THREAD

**Issue by TrigonaMinima** [open-nomie/nomie#114]
So I tried IFTTT to post a simple note using a generated API key. It didn't work. I then tried a direct POST request using a python script, but it gave a `500 Server Error: Internal Server Error for url: https://nomieapi.com/log`. I've also enabled "Auto Accept". Looking at the exact error, I get the following message:

```
{"success":false,"results":{"message":"Invalid api_key"}}
```
I didn't make any changes to the api key so I don't know why it's giving an invalid api_key error.

Nomie version: 5.3.3
Storage: blockstock based

**Comment by huberf** [comment]
Did you set the POST type to `application/json`. I've run into this issue when not using that type.

**Comment by TrigonaMinima** [comment]
Hey, thanks. The option of `application/json` works in my script. I had selected it in ifttt but it didn't work yest. Today I tried with a different api key in ifttt and it worked.
