### ISSUE TITLE
Multiple storage/sync

### ISSUE THREAD

**Issue by thejeshgn** [open-nomie/nomie#12]
I would love to have multiple storage/sync mecahnism. If you can make the interface generic. May be the community can add different storage/sync backends.

**Comment by brandoncorbin** [comment]
I'm going to work on getting local and blockstack broken into their own modules/storage/engine - since one requires auth and the other doesn't, it should have pretty good coverage for other potential storage engines (thinking dropbox, google drive)

**Comment by thejeshgn** [comment]
Yes, I would love to do CouchDB integration once you expose the interface.

**Comment by brandoncorbin** [comment]
It's more flexible now - you can look at both storage/engine.blockstack.js for one that requires user interact, and storage/engine.localforage.js for one that has no user interaction...
