### ISSUE TITLE
"Importing from API" only seems to work on mobile

### ISSUE THREAD

**Issue by Ipsquiggle** [open-nomie/nomie#120]
I use the API with IFTTT, and data submits reliably.

Working on mobile:
When I open v5.nomie.app on mobile (Android, Firefox), the toast with, "Importing X Notes from the API..." and the notes succesfully import. Sometimes this requires refreshing the page.

Not working on desktop:
When I open v5.nomie.app on my desktop browser (Windows, Firefox), I never get the importing toast and the notes don't seem to import ever.

**Comment by brandoncorbin** [comment]
Is it the same API key on Desktop and Mobile?  If not, does the Desktop ever load data from the API, and just not show the display?

**Comment by Ipsquiggle** [comment]
Aha. In the process of confirming these things, I discovered that while "auto accept" is checked on mobile, it's not checked on desktop. So scratch this bug, but I'd say there's a bug that this particular setting did not synchronize between devices. Is that intentional? (Shall I open a new bug?)

**Comment by brandoncorbin** [comment]
Thanks for the update, no I want to keep this data at the device level for those that have multiple api's for multiple devices.
