### ISSUE TITLE
Feature request: WebDAV storage backend

### ISSUE THREAD

**Issue by tholop** [open-nomie/nomie#121]
It would be nice to be able to synchronize the data on a WebDAV backend (e.g. a personal Nextcloud instance), instead of having to put it on a blockchain. I don't know if the remote CouchDB backend beta works well (it still shows `Not good for multiple devices`), but WebDAV seems widely adopted by apps that synchronize multiple devices.

Thanks for this great app!

**Comment by brandoncorbin** [comment]
Hey Tholop, super interesting idea. I've been searching for another data store to add, and this might just be the one to play with. 

But... When you use blockstack, your data is not stored on a blockchain. Blockstack Storage only uses the blockchain for authentication. All of the files and data are stored encrypted on Blockstacks free Gaia hub instance.

**Comment by tholop** [comment]
Glad it might be useful! Joplin, the open-source note-taking app, is an example of app using WebDAV synchronization: https://github.com/laurent22/joplin#webdav-synchronisation. I'm happy to help if you need testing/documentation at some point.

**Comment by brandoncorbin** [comment]
One of the biggest problems with this approach (beyond the unknown performance) is the WebDav servers will need to support CORS headers properly - apparently Nextcloud doesn't support it.

**Comment by tholop** [comment]
That's unfortunate. It seems that this project runs into the same issue: https://github.com/johannesjo/super-productivity/issues/159#issuecomment-706616475, although there is a Nextcloud plugin that brings support for CORS headers.

Thanks for having taken the time to look into it though!

**Comment by brandoncorbin** [comment]
I'm going to be closing this. I'm currently looking into a new storage structure that would lead us to Nomie 6, which will bring additional ways of accessing Nomie's data and not require blockstack.
