### ISSUE TITLE
Pick From List seems broken

### ISSUE THREAD

**Issue by Neverstop7** [open-nomie/nomie#122]
Hello!
I have tried to create a "Pick from list" tracker. How am I supposed to create a new line? I've tried to press 'Enter' but nothing happens. Should I separate items with a semicolon? I am able to create only a single item in the list.
Thank you in advance

**Comment by brandoncorbin** [comment]
What device are you using?

**Comment by Neverstop7** [comment]
I have finally figured it out. I use Mozilla Firefox. The 'enter' button doesn't work so you can't create a new line. However if I use Google Chrome everything works right,
