### ISSUE TITLE
Can't login after choosing a wrong pin

### ISSUE THREAD

**Issue by xplosionmind** [open-nomie/nomie#127]
When setting up my PIN to access the app, I suppose I mistyped the PIN and now I can't log in since the PIN results wrong. Is there a way to reset everything and start from scratch? I have no data on the app

**Comment by brandoncorbin** [comment]
First you should login to Nomie with a Chrome or Firefox on the desktop. Once you're in your Blockstack version of Nomie:

Right click anywhere on the page and select "Inspect". 
Select the "Console" tab in the newly opened inspector panel
Paste the code below into the bottom of the console window next to the >
Hit Enter

See the steps: https://shareking.s3.amazonaws.com/pb-1CltI2PSZV-1601997783.png

Copy from below this line ---

```
async function unlock() {
let path = "v5-data/meta.json";
let file = await blockstack.getFile(path);
let done = await blockstack.putFile(path, JSON.stringify({ ...JSON.parse(file || {}), ...{ lock: false, access_pin: null } }));
done ? window.location.reload() : alert("error");
}
unlock();
```
