### ISSUE TITLE
Bug: Units are not stored with tracker entries

### ISSUE THREAD

**Issue by jsejcksn** [open-nomie/nomie#130]
If entries are recorded for a tracker in one unit (e.g. oz), and then the unit is changed later (e.g. mL) and more entries are recorded, then all entries appear in the current unit setting (mL) in history and calculations.

Fix: The current unit setting should be recorded along with the numeric input for each entry.

Display and calculations might or might not include conversion, but that is a separate concern.

**Comment by brandoncorbin** [comment]
Hey Jejcksn - UOM has no affect on calculations. Values are stored however they're added to the note, and the UOM is used only for formatting the display of that value.

**Comment by jsejcksn** [comment]
> UOM has no affect on calculations

@brandoncorbin That's the bug.

**Comment by brandoncorbin** [comment]
This is how Nomie has worked for the last 6 years, and unless a massive refactoring happens in Nomie 6 - I don’t see it changing.

**Comment by jsejcksn** [comment]
@brandoncorbin No worries.

When I started experimenting with Nomie for the first time today, it was the first issue I encountered. I just wanted to make sure it wasn't overlooked.
