### ISSUE TITLE
Customize the range of sliding scale in tracker

### ISSUE THREAD

**Issue by jtrakk** [open-nomie/nomie#142]
For example, If I want to try rating out of 100 instead of out of 10, that would be a nice option. Or starting at 0 instead of at 1.

**Comment by Neverstop7** [comment]
In my opinion, we as human beings are not able to rate something precisely in a scale of 1 to 100

**Comment by jtrakk** [comment]
It could be any number: out of 5, out of 7, out of 13, out of 100.

**Comment by mike-curtin** [comment]
You are able to create your own trackers. For your example "0-5, 0-11, 1-5, 1-100, -30-30..." , you can set all of those separately, to different trackers. You can also start at 0, or 1, or -8, etc . As well as Ignore 0 values.

The only issue I had is actually setting the "min" number to a negative. Tapping the ".-" key only yields a "." for "min", whereas "default value" and "range step" toggle between the "." and "-". For testing, I was able to voice-to-text to enter the negative value for the "min" number. See screenshot.

Is this what you are referring to?

![Screenshot_20210207-164703_Chrome](https://user-images.githubusercontent.com/12864451/107160472-652c9a00-6964-11eb-95d2-0e436196f5c1.jpg)

**Comment by jtrakk** [comment]
You're totally right. Sorry for the noise.
