### ISSUE TITLE
Can't use flag emoji for trackers

### ISSUE THREAD

**Issue by grimmn** [open-nomie/nomie#17]
I tried to use a flag emoji for a tracker but it only came up as one of the Regional Indicator Symbols used for that flag instead of the proper emoji.

**Comment by brandoncorbin** [comment]
I’ve learned that emojis can take up multiple character counts. Originally I had the emoji input set to - max length of 1, and noticed some emojis didn’t work. I increased it to 3 and thought that’d cover it. Apparently not!! Will get this fixed.

**Comment by brandoncorbin** [comment]
Fixed in v4.1.16
