### ISSUE TITLE
Double Tap = 4 counted

### ISSUE THREAD

**Issue by daniel-hermann** [open-nomie/nomie#22]
I have a "Single Tap" tracke with "Save on Tap" activated. Sometimes I double Tap (Tracker is coffee, when I drink a double espresso I double tap).

However when double-tapping it creates 2 "coffee" entries with count 2 each, so in total 4 coffees instead of 2

EDIT: Firefox on Android, not tested any other system

**Comment by brandoncorbin** [comment]
I’m guessing you’re coming from Nomie 2? 

I spent a ridiculous amount of time and code making Nomie 1 and 2’s Button tapping stupid fast. I didn’t do it in Nomie 3, and the Nomie 3 TraclerButton is what made it in Nomie 4. 

I’ve hooked up a new touch event module, so I might treat double tapping as some other action. 

Short answer: not sure what the solution is yet.

**Comment by daniel-hermann** [comment]
@brandoncorbin I think the issue is only partly solved.

When doubletapping one item it is solved.
When tapping two different items too fast it counts the first item twice.
