### ISSUE TITLE
Iphone not pulling latest data.

### ISSUE THREAD

**Issue by bsq** [open-nomie/nomie#24]
I use the iphone version and also access Nomie via a computer browser. I noticed that when I update on the browser the iphone version often does not have the updates. If I then track something on the iphone it overrides any changes made on the web version.

**Comment by brandoncorbin** [comment]
Valid issue. Need to think about the best way to pull the latest from blockstack before adding the new long and saving it back to blockstack.

**Comment by brandoncorbin** [comment]
Added a setting for "Aggressive Sync" - enable it. Basically, now every time Nomie loads "getToday()" it will download the most recent ledger file .. so if you've changed something it should be synced. Note, this might slow some things down.
