### ISSUE TITLE
Export not exporting 

### ISSUE THREAD

**Issue by brandoncorbin** [open-nomie/nomie#26]
Exporting does t seem to do anything when using BlockStack.

Error also happening on Settings page.. Looks related.

**Comment by trych** [comment]
Is this supposed to work now? I only get an "Export Done!" popup but nothing else happens. What is expected to happen?

**Comment by brandoncorbin** [comment]
Yes, it should be working. What happens when it’s done depends on the browser you’re using. 

IOS should ask what you want to open it with.  Chrome should download the file

What device/browser are you using?

**Comment by trych** [comment]
Ok, it does work on Chrome indeed.

It does *not* work for me on

- Firefox 68.0.2, macOS 10.13.6
- iOS 11.14.1, iPhone 5S
