### ISSUE TITLE
Add option to use Metric System

### ISSUE THREAD

**Issue by luanmuniz** [open-nomie/nomie#29]
I live in Brazil and we use the Metric System. Water tracking, for example, is measured in Liters here.

I'm glad to send a PR for this but I don't know the codebase. Can you guys guide me a little on how should this be done?

Thanks

**Comment by brandoncorbin** [comment]
A trackers units of measurement is configurable. Long press the tracker, select "Edit", pick from the Unit of Measure option.

**Comment by brandoncorbin** [comment]
But your comment is still valid, I'm going to set the uom to nothing - just a plain number. This way it can be whatever the users want's it needs to be. 

Side note: Nomie's UOM system is pretty stupid and does no real conversions, just formatting.

**Comment by luanmuniz** [comment]
I'm using it on my browser. How can i trigger the long press?

**Comment by brandoncorbin** [comment]
@luanmuniz what happens when you click and hold a tracker button?

**Comment by luanmuniz** [comment]
The style of the block keep as "pressed" but when i release, nothing happens, not even the modal to add an entry opens.

**Comment by brandoncorbin** [comment]
@luanmuniz what browser are you using?

**Comment by luanmuniz** [comment]
@brandoncorbin I'm so sorry. It was not working because of one of my extensions. It was getting an error. It's working as it should.

Thanks for your attention and Sorry for the trouble.

**Comment by brandoncorbin** [comment]
@luanmuniz glad that got worked out, but I'm curious which extension would cause a long press from not being fired...

**Comment by tbm** [comment]
> But your comment is still valid, I'm going to set the uom to nothing - just a plain number. This way it can be whatever the users want's it needs to be.

Did you forgot to do that?  I used Nomie for the first time yesterday (v5) and weight was in lb and water in ounces.
