### ISSUE TITLE
[UI/visual] inconsistent dark mode on wide screens

### ISSUE THREAD

**Issue by huberf** [open-nomie/nomie#3]
This is a very minor issue but the top bar has the bottom grey margin and black background only extend to the set max-width when it should fill the entire width of the screen when Dark Mode is enabled. I'll look into the fix (likely just a couple line change/component restructure) but unfortunately am very busy the next two weeks so may not be until after then that I could look into this myself.

![image](https://user-images.githubusercontent.com/10063850/62012107-c2704a00-b136-11e9-904c-53dbd7da5e77.png)

**Comment by brandoncorbin** [comment]
Thanks Noah, this this has been fixed and pushed to develop - 4.1.1
