### ISSUE TITLE
Nomie needs a way to mass edit Tag data.

### ISSUE THREAD

**Issue by sayo-melu** [open-nomie/nomie#34]
It is difficult for normal users to know what 'Tag' is when adding trackers, and it is also hard for users to change the 'Tag' name on web (they have to download the backup and change it manually, then import).

If it is possible to generate a random Tag when adding a new Tracker, make it easier to manage trackers?

**Comment by sayo-melu** [comment]
If that could be completed, Lable and Tag could be combined in to one.

**Comment by sayo-melu** [comment]
Well, I was always confused when writing a note with Tag, because I could not remember what the Tag is, and there is no way to find it again after the Trigger is added.

**Comment by sayo-melu** [comment]
That could be much better, thanks.

**Comment by sayo-melu** [comment]
@brandoncorbin I changed the issue title for better description.

**Comment by brandoncorbin** [comment]
This will be in the dev branch shortly 
![image](https://user-images.githubusercontent.com/195692/63904955-a3d4cb80-c9e0-11e9-9383-0a807865fa56.png)

**Comment by sayo-melu** [comment]
Thanks, waiting for master branch.
