### ISSUE TITLE
API Date Formatting Issue

### ISSUE THREAD

**Issue by PurpleCapedCrusader** [open-nomie/nomie#36]
I'm using iOS Shortcuts to log my steps and distance walked for the previous day. I can get my steps and distance walked into the app via the api without issue. I've tried formatting the date several ways but I keep getting "Invalid Date from api" in Settings > Nomie API > Captured. 

What date formatting should I use with the API?

**Comment by brandoncorbin** [comment]
I just noticed it this morning with my Fitbit doing the same thing. It's a bug and I'll look into it this weekend.

**Comment by brandoncorbin** [comment]
Just looked and tested it locally, and any valid constructor to Javascript's Date Object should be valid..

**Comment by PurpleCapedCrusader** [comment]
Awesome! Just tested and it works great!

**Comment by brandoncorbin** [comment]
SWEET!
