### ISSUE TITLE
swiftkey keyboard doesn't work in ios

### ISSUE THREAD

**Issue by yangkennyk** [open-nomie/nomie#37]
swiftkey doesn't input anything when you try to use it in the ios version.

I have to switch to the the default ios keyboard to input data it seems

**Comment by brandoncorbin** [comment]
Does Swiftkey work if you use it with other websites that have been "added to home screen"

**Comment by yangkennyk** [comment]
> Does Swiftkey work if you use it with other websites that have been "added to home screen"

hmm. so I just tried and it seems that "add to home screen" seems to just pull up safari on websites but nomie seems to load it as an "app" style?

so I'm not quite sure as I don't have any other "add to home screen" apps. 

is there a site I can test it on where it it'll load it similarly to nomie?

**Comment by brandoncorbin** [comment]
Check Twitter or Facebook, both of them should have the PWA like functionality.

**Comment by yangkennyk** [comment]
ok. never mind. now it started working! 

not sure what happened but another issue is that the the padding/margin doesn't account for extra height when using Swiftkey

https://drive.google.com/file/d/1qlzIckwqj-3ttgdfPqQtA1GNSur4gni-/view?usp=sharing
