### ISSUE TITLE
iPhoneX safe-zone being ignored

### ISSUE THREAD

**Issue by yangkennyk** [open-nomie/nomie#38]
the app seems to cut out on iphone x

so there is a gray bar at the top and the bottom has the gray rectangle that blocks the middle buttons

![image](https://user-images.githubusercontent.com/6680040/64058166-8e33e300-cb53-11e9-9a1d-4b13ae01d485.png)

**Comment by PurpleCapedCrusader** [comment]
I have an iPhoneX and mine is the same.

**Comment by bsq** [comment]
Same here, except note it only happens on the app version, not on web version on iPhone X.

**Comment by brandoncorbin** [comment]
Got this fixed last night 🤞 and will be pushed to master/production later today.
