### ISSUE TITLE
FAQ information invisible in dark mode

### ISSUE THREAD

**Issue by ipalindromi** [open-nomie/nomie#4]
![image](https://user-images.githubusercontent.com/1351129/62086727-ec079f00-b224-11e9-95c3-c4bcd8786d2b.png)

When in dark mode, the FAQ text is invisible.

I also noticed the dashboard page has white spaces when in dark mode.

![image](https://user-images.githubusercontent.com/1351129/62086842-486abe80-b225-11e9-98a4-d6b75b57f071.png)

**Comment by ipalindromi** [comment]
I don't know Svelte well, but these look like basic css issues. I think I've tracked them down. I can put up a PR, if you'd like.

**Comment by brandoncorbin** [comment]
Thanks for the faq catch, I can get that fixed right quick. It will be in the dev branch this evening. The board background issue was caught by Noah this morning. It’s fixed in Develop.

**Comment by brandoncorbin** [comment]
Fixed in 4.1.4... This will also fix any other list item that had a description too.
