### ISSUE TITLE
Aggressive Sync is WAY TOO AGGRESSIVE!

### ISSUE THREAD

**Issue by PurpleCapedCrusader** [open-nomie/nomie#42]
It’s the field at the bottom of the tracker main page. It flickers very fast and never stops. I have to press a letter several times before it appears in the field. It’s like it reloads on a loop or something. I’m on an iPhoneX, if that makes any difference.

**Comment by brandoncorbin** [comment]
Any way of getting a screen recording of this?

**Comment by PurpleCapedCrusader** [comment]
Sure, here’s a video link. 

https://drive.google.com/file/d/1CX7tPLUnAnBzPVsdnlzd4hDQ549e1H0U/view?usp=drivesdk

**Comment by brandoncorbin** [comment]
Well hell, that's crazy.  

is this only happening on the iPhone? 
Is the App added to home screen? 
does this happen if access it via the browser?

I've replaced the wonky saving timeout - which could cause the component to react multiple times, but I'm not having any luck reproducing the craziness in this video.

**Comment by PurpleCapedCrusader** [comment]
It does it in Safari as a regular site and as a home screen app. It also does it in Chrome.

**Comment by brandoncorbin** [comment]
Still unable to reproduce on Chrome or Safari - let's try once more thing to narrow it down.  Start a private browser window... Go to open.nomie.app - go through the setup and select Local Device only...  

Does it still do it? If not, then there's something going on with your specific data.

**Comment by PurpleCapedCrusader** [comment]
While in a safari private browser window using local data, there is no flicker. There’s a single reset of that text when the page loads and reloads.

Looks like it’s my data.

**Comment by brandoncorbin** [comment]
At least this helps us narrow down what's going on a little bit. 

Here are some of the things I can think would cause a component to react.

- Nomie API auto importing (but should only happen when first launched)
- Nomie checking if the day has changed (but this is only every few minutes)
- If Aggressive Sync is enabled in Settings
- URL Commands being executed (but I haven't told anyone about those so I doubt you're doing that). 


What about

**Comment by PurpleCapedCrusader** [comment]
I just turned off Aggressive Sync and it stopped.

**Comment by brandoncorbin** [comment]
Ok, that's something that I can attack. Thanks for the help Alex!

**Comment by PurpleCapedCrusader** [comment]
👍
