### ISSUE TITLE
Moving history point to last month

### ISSUE THREAD

**Issue by daniel-hermann** [open-nomie/nomie#44]
When trying to change the date of a history point it only works in the same month.

Moving a point to the 9/1/2019 works, but 8/31/2019 does not work. It sys log updated but the tracker point stays on the same date.

**Comment by brandoncorbin** [comment]
I’m working on a full log editor modal that will bring all the editing into a single UI like Nomie 2 - I’ll fix the month bug too. I expect it to be in dev tonight, master this weekend
