### ISSUE TITLE
Double Tap - only partly solved

### ISSUE THREAD

**Issue by daniel-hermann** [open-nomie/nomie#48]
@brandoncorbin I think the issue #22 is only partly solved. I do not know how to reopen the issue, and I guess you don't see posts in closed issues?

When doubletapping one item it is solved.
When tapping two different items too fast it counts the first item twice.

**Comment by brandoncorbin** [comment]
Hey Daniel, with this new architecture it'd take a lot of hacking to get it to respond as fast as Nomie 2. I'm closing this with a won't fix (anytime soon).
