### ISSUE TITLE
Remove the always-visible scrollbar

### ISSUE THREAD

**Issue by sammosna** [open-nomie/nomie#49]
It would be nice to remove the always-visible scrollbar from the UI, like here:

![scrollbar](https://i.ibb.co/HXcSqF2/Schermata-2019-09-13-alle-12-27-27.png)

**Comment by brandoncorbin** [comment]
What browser and OS?

**Comment by sammosna** [comment]
Google Chrome on macOS

**Comment by brandoncorbin** [comment]
mmm.. I'm able to reproduce this if I got to Mac Settings and set the scroll bars to always on - do you happen to have that enabled? 

![image](https://user-images.githubusercontent.com/195692/65037935-cb062500-d91c-11e9-95d3-556be0935879.png)
 
![image](https://user-images.githubusercontent.com/195692/65038054-13254780-d91d-11e9-8f83-d9a88dc2c7f8.png)

Then this happens 
![image](https://user-images.githubusercontent.com/195692/65038094-2801db00-d91d-11e9-8dcd-143e3e376bce.png)

**Comment by sammosna** [comment]
Yes, I have it enabled. I tried putting the `overflow` to `hidden` to the `.n-hscroller.svelte-1u6h6fy` class and scrollbars disappear

**Comment by brandoncorbin** [comment]
Ok, for whatever reason this report kept chewing at the back of my brain... but I managed to hide the scrollbars while still allowing you to  scroll. Note, this only works on Chrome/Safari - It will be in the dev branch shortly, and in master this weekend.
