### ISSUE TITLE
Add multi-language support.

### ISSUE THREAD

**Issue by sayo-melu** [open-nomie/nomie#50]
Add a multi-language protocol, and I can provide a Chinese translation.

**Comment by sayo-melu** [comment]
In `src/lang/en.js`

```js
board: {
			'board-empty': 'Sure is Empty!',
			'edit-board': `Edit Tab`,
			'board-label': 'Board Label',
			'create-custom-tracker': 'Create Custom Tracker',
			'add-existing-tracker': 'Add Existing Tracker',
			'browse-starter-trackers': 'Browse Tracker Library',
			'add-a-board': 'Add a Tab',
			'add-a-board-description': `Tabs help you organize your trackers. For example: social, food, and fitness can contain trackers specifically for those activies. You can have the same tracker on multiple tabs.`,
			'board-input-placeholder': 'Tab name or Emoji 👍',
```

What's the difference between Board and Tab? Are they the same?

**Comment by brandoncorbin** [comment]
I’ve called them boards since Nomie 2 - but for new users Board doesn’t mean anything. And I assume that board would be hard to translate. So this weekend I decided to start calling them Tabs - open to suggestions though.

**Comment by sayo-melu** [comment]
In Chinese, tab, tag, label share the similar meaning '标签'.

To reduce the confusion, can I directly translate the 'label' to '名称' (name), while 'tab' can be translate to '标签页' (tagged page) as web browsers do.

**Comment by brandoncorbin** [comment]
Yes, going with the browser “tagged page“ makes the most sense for what they are.

**Comment by sayo-melu** [comment]
How about the 'label' to '名称' (name)?

**Comment by brandoncorbin** [comment]
That feels accurate.

**Comment by sayo-melu** [comment]
#55 Chinese translation (partial).

**Comment by brandoncorbin** [comment]
Thanks for your work Sayo-melu! I've added this functionality to the develop branch (in settings). 

Obviously while I'm in crazy dev mode - the language is going to be changing often -  I've made it so it will default to English if a translation isn't available. 

Thanks again!
