### ISSUE TITLE
Settings screen unclear as to whether using cloud storage

### ISSUE THREAD

**Issue by JohnVeness** [open-nomie/nomie#51]
Hello. First time user of the app here, so these are initial impressions.

I chose to use Local storage when I first started and added the recommended trackers. Then went into Settings.

Even though I knew I had picked Local, the Settings screen worried me with the text "Use Cloud". I am a native English speaker, but even so I wasn't sure if this meant I was currently using Cloud or not. Its position on the right-hand side made it look like this was the current setting.

Maybe if the text was changed to "Switch to cloud storage" or similar, maybe in a smaller font, and across the full width (underneath rather than alongside Local) it'd be clearer.

Many thanks for making this app.
![](https://i.imgur.com/ZH0GETI.png)

**Comment by brandoncorbin** [comment]
100% agree.
