### ISSUE TITLE
Add some more (optional) example trackers

### ISSUE THREAD

**Issue by JohnVeness** [open-nomie/nomie#52]
When adding a tracker, one is immediately put into what I might describe as an "advanced" or "custom" mode. This power is great, but as a first time user I was expecting to see a gallery of premade example trackers to choose from. And a custom tracker option at the end.

**Comment by brandoncorbin** [comment]
Thanks for the recommendation, and you are right - the current editor is the  advanced tracker editor.  The Simplified Editor and pre made libraries haven't made it over from nomie 3 yet... Soon tho.

**Comment by JohnVeness** [comment]
Ah thanks. I haven't used previous versions.
