### ISSUE TITLE
Improve "First Book Created" text

### ISSUE THREAD

**Issue by JohnVeness** [open-nomie/nomie#54]
When first using the app and going into Settings straight away, next to "First Book Created" it says "NaN years ago", which I expect can be improved.

Incidentally I don't know what a "book" is in this context. Maybe this can be explained somehow in the app or in the FAQ.

After using a couple of trackers, it now says the first book was created  17 days ago, even though I've just started using the app. Maybe because it is the 17th day of the current month?

Anything you can do to improve clarity on this text would be very welcome!
![](https://i.imgur.com/ZH0GETI.png)

**Comment by brandoncorbin** [comment]
It should just be removed... It was left over from when I was testing if my imports were working... It offers little value, and clearly it's not working right.

A "Book" is what I'm calling a month of data. Each month a new file is created, and when you track it's added to that "book"..
