### ISSUE TITLE
Add advance tracker arrangement

### ISSUE THREAD

**Issue by Logic530** [open-nomie/nomie#56]
Make it possible for users to rearrange trackers. This could be done by hold and drag or drag in a "arrange mode".
Also, add folders.
This will make it more convenient to organize trackers and saves space.

**Comment by sayo-melu** [comment]
The Trackers are arranged in alphabet, if you want to sort the trackers, you can put them in different Tabs.

The Folder, do you mean Tab? There really should be way to rearrange it.

**Comment by brandoncorbin** [comment]
If you’re brand new to Nomie. Go to the settings and enable Tracker Board Tabs. This will give you the “folders” you’re looking for. You can sort and range trackers on them however you like. Note: a single tracker can be in multiple tabs.
