### ISSUE TITLE
iOS location alert on open

### ISSUE THREAD

**Issue by sammosna** [open-nomie/nomie#57]
Every time I open the "Progressive web app" (I've just pressed the _add to homescreen_ button from Safari), it shows me the alert about location access. Is it possible to get rid of it?
![416AC63A-DDAE-49FB-BE46-2C4B5F31C8C9](https://user-images.githubusercontent.com/6976083/65412367-5c7b0880-ddef-11e9-9caa-ae5a1fdac107.PNG)

**Comment by brandoncorbin** [comment]
There’s a way - I don’t remember what I did to to Always allow. I’ll keep looking around

**Comment by joshhouseholder** [comment]
In the settings. Safari and location. You can set to always allow, but it does it for every site.

[Joshua Householder - Chat @ Spike](https://www.spikenow.com/?ref=spike-organic-signature&_ts=6aebh)	[6aebh]

On September 23, 2019 at 22:05 GMT, Brandon Corbin <notifications@github.com> wrote:

There’s a way - I don’t remember what I did to to Always allow. I’ll keep looking around

**Comment by sammosna** [comment]
And isn't it possible to do it site-specific?

**Comment by joshhouseholder** [comment]
Sorry for the email junk. Won’t happen again. 
It’s site specific in safari. No idea how to do it in pwa’s.

**Comment by brandoncorbin** [comment]
Is this still an issue for you?

**Comment by sammosna** [comment]
Edited in safari’s settings
