### ISSUE TITLE
Import from Nomie 2 backup don't imports boards

### ISSUE THREAD

**Issue by mcorossigo** [open-nomie/nomie#60]
Hello @brandoncorbin 
I'm a long time Nomie 2 user (which for me, is still the ultimate unparalled tracker), but the rise of some glitches convinced me to to try to upgrade to Nomie 4.

Using the import from backup, Nomie 4 doesn't pick up the boards/tabs, while the JSON backup has a properly populated groups field.

Is this a bug or indended behaviour?

The problem seems to be platform independent.
Nomie 4 version used: 4.3.0
Thank you!

**Comment by brandoncorbin** [comment]
Can you go into Settings and make sure that “Board Tabs” is enabled? I haven’t tested the 2 import since adding that feature. If that doesn’t solve it, and export of Nomie 4 would confirm 100% if the boards made it.

If they didn’t, then it’s a bug.

**Comment by mcorossigo** [comment]
> Can you go into Settings and make sure that “Board Tabs” is enabled?

It does'n fix the problem. The import info still reports 0 importable Boards.
Are you planning to look into this, or it's better for me to make a Nomie 2 -> Nomie 3 -> Nomie 4 kind of thing?

**Comment by brandoncorbin** [comment]
I won’t be able to get to it until Sunday… so it won’t make it in the major release this weekend.  Manually massaging the data might be the best bet.. Look at how Nomie 4 exports boards. Then take your Nomie 2 board data and format it accordingly. Not ideal, but if you want to get going on it - it’s the best option.
