### ISSUE TITLE
All icons are unsupported

### ISSUE THREAD

**Issue by mcorossigo** [open-nomie/nomie#61]
Hello,
as you can see in the screenshots, all the icons (which I suppose are font icons) appear unsupported.
The problem appears on iPhone both as a Home web app and in Safari.

|Trackers|Settings|
|--|--|
|![F538FB17-44EB-4040-9C53-B65E2CC284F3](https://user-images.githubusercontent.com/36412793/66209256-41de4480-e6b7-11e9-8aa7-589e07d29289.png)|![F9F069E0-9138-4268-A885-5B422709CF31](https://user-images.githubusercontent.com/36412793/66209258-41de4480-e6b7-11e9-881e-8f02165fba53.png)

iPhone: 6S Plus
iOS: 13.2
Nomie 4: 4.3.0

Please, let me know if there is any other information that can help you.

**Comment by brandoncorbin** [comment]
Do you have any ad blockers on? A pihole maybe? 

Nomie uses the ZMDI font icon set - I’m wondering if its getting blocked somehow. 

 Ill keep trying to reproduce it,  but so far not having much luck.

**Comment by mcorossigo** [comment]
> Do you have any ad blockers on? A pihole maybe?

Yes, not a Pihole, but Firefox Focus setup as a content blocker, as explained here: https://support.mozilla.org/en-US/kb/focus#w_use-firefox-focus-with-safari

Disabling it actually fix the problem.

**Comment by brandoncorbin** [comment]
Not much we can do about it. All icons are served from the domain (not using the CDN) so it's clearly stopping certain web fonts from loading...
