### ISSUE TITLE
Feature request: Remove right click event from trackers

### ISSUE THREAD

**Issue by mcorossigo** [open-nomie/nomie#62]
On desktop right-clicking on a tracker spawns the usual context-menu but also trigger the tracker behavior.

I think that only left click should count as a click.

**Comment by brandoncorbin** [comment]
This will be hitting production this weekend.

**Comment by mcorossigo** [comment]
Now I see that I very badly worded my request.
It is my opinion that users should alway be able to spawn the context menu on websites. The problem was that I wasn't able to to that on a Tracker button, without it _also_ registering an event.

This issue was about removing this behaviour, since **only** the left click should count as a user action.

I think that your fix implemented here https://github.com/open-nomie/nomie/commit/555579d5e700c5ff29087dbb69efceddf59da0b8#diff-99e2c095d4dcb00199aa3493e86e253d should be reverted and a click event should be dispatched only with a left click.

The final behaviour, which I beleave to be the most common/predicatble is:
 - right click on tracker button: tracker button does **not** trigger and the context menu is showed
 - left click on tracker button: tracker button is triggered

**Comment by brandoncorbin** [comment]
Thanks for the feedback. But the contextual menu on longpress had been bugging for a while, and was the chopping block before this post. Certain browsers automatically assume a long press as a right click, and it's annoying. It will stay this way for now.
