### ISSUE TITLE
On an iPhone, how can I save the downloaded CSV?

### ISSUE THREAD

**Issue by trych** [open-nomie/nomie#63]
On an iPhone (iOS11), when I go to `Download CSV`, it sends me to what looks like a html page with a table containing my data. From there I seem to be unable to save the data somehow. Same if I go to Backup, then I see what looks like an html page spelling out an entire JSON structure for me.

Is there any way to retrieve these data as actual files? I would love to start using nomie in the class I am currently teaching, but I need a working export / download functionality.

Thanks!

**Comment by joshhouseholder** [comment]
Download a JSON app. Copy and past it there depending on the app it might not convert everything correctly. 
iOS 13 fixes this problem. 
I believe it’s older versions iOS that doesn’t work well with PWA’s.
