### ISSUE TITLE
Feature request: show file name of backup when downloading

### ISSUE THREAD

**Issue by mcorossigo** [open-nomie/nomie#65]
When saving a JSON backuo on iOS 13, it shows this:
![IMG_3485](https://user-images.githubusercontent.com/36412793/67426517-8a17c500-f5da-11e9-86c9-ae9434408f5c.PNG)

It would be nice if it could show the name of the file.

**Comment by brandoncorbin** [comment]
For some reason iOS isn't picking up the filename  ... I'm not sure what else I can pass to the download to make it read.
