### ISSUE TITLE
Feature request: reorder boards

### ISSUE THREAD

**Issue by mcorossigo** [open-nomie/nomie#66]
My two more commonly used boards are far away from each other, and since my board tab overflows I always have to swipe left or right.

It would be great if they could be manually ordered.

**Comment by mcorossigo** [comment]
In https://github.com/open-nomie/nomie/commit/0ea54a74f164a977d950da97eeea00a31f0fa7ce the description says:

```
## Enhancements

-  Board Sorting

...
```

Did you mean Tracker sorting inside of a Board, not actual sort of Boards (from now on referred as Tabs), right?

If not, I'm not sure how the feature works in Nomie 4.4.11

**Comment by brandoncorbin** [comment]
Board sorting has been added to 4.5, and tracker sorting (with in a board) has been simplified so it works on mobile

**Comment by mcorossigo** [comment]
> Note that Boards will still be called boards in code so it will still be used interchangeably on github...

Not a problem, but maybe you want to use Tabs in the Changelog.

> Board sorting has been added to 4.5

Nice, although it only appears to be available with 3+ Tabs (not two)

![IMG_118DB960A2DF-1 copia](https://user-images.githubusercontent.com/36412793/69065141-8b90ad80-0a1f-11ea-8980-3926421b9cf8.jpeg)

Is this intentional?

**Comment by brandoncorbin** [comment]
It is, but I'm not opposed to changing it.. Mainly, I want to keep advanced features and functionality away from new users to limit confusion and feature overload.
