### ISSUE TITLE
Feature request: manage up two emoji for tracker

### ISSUE THREAD

**Issue by mcorossigo** [open-nomie/nomie#67]
Unlike Nomie 2 icons, Nomie 4 emoji icons offers (while in greater number) lower variability. If you find the perfect emoji fine, otherwise you just get a generic one that somewhat feels wrong.

So, to improve visual characterization, I tried using two emojis. But they seems to always pile up:

![IMG_3567](https://user-images.githubusercontent.com/36412793/67427436-6b1a3280-f5dc-11e9-8dcb-cd6db8ad2f24.PNG)

Can you properly manage up to two emoji instead of one?

**Comment by brandoncorbin** [comment]
Doubled up... Coming this weekend.

![image](https://user-images.githubusercontent.com/195692/67914303-25261700-fb66-11e9-98ce-1d89f5d24a2f.png)
