### ISSUE TITLE
Feature request: dots on bottom of the tracker

### ISSUE THREAD

**Issue by mcorossigo** [open-nomie/nomie#68]
Nomie 2 had the beautiful visual feature to add points on the bottom of the tracker to get rapid grasp of when you tracked last time:

![IMG_3568](https://user-images.githubusercontent.com/36412793/67427814-2f339d00-f5dd-11e9-987b-8a42dec465c1.PNG)

Can it be added to Nomie 4?

**Comment by brandoncorbin** [comment]
Oh the good old "time" dots. I'd be interested to see how this preforms with Svelte compared to Nomie 2's Angular, which was a nightmare.

**Comment by brandoncorbin** [comment]
The balls are back! Will be hitting production this weekend. 

![image](https://user-images.githubusercontent.com/195692/67914238-e7c18980-fb65-11e9-98ba-9d375a4623a4.png)
