### ISSUE TITLE
Custom Positivity not applying for "Hour of Day" 

### ISSUE THREAD

**Issue by mcorossigo** [open-nomie/nomie#70]
Hello @brandoncorbin 

I'm having an hard time understanding the custom positivity setting.

This is an example:

| Tracker config | History |
| -- | -- |
|<img width="430" alt="Schermata 2019-10-25 alle 14 40 51" src="https://user-images.githubusercontent.com/36412793/67572054-b7c55100-f735-11e9-99e3-bf948582d73a.png">|<img width="1011" alt="Schermata 2019-10-25 alle 14 41 40" src="https://user-images.githubusercontent.com/36412793/67572055-b7c55100-f735-11e9-8264-d4c4e6ef5389.png">|

I expected all the items being created in the `21` hour (which is obviosly greater than `20`) to be get a `-1` positivity.

Am I missing something?

**Comment by brandoncorbin** [comment]
No, that looks like a bug!

**Comment by brandoncorbin** [comment]
The bug has been found! the fix will hit dev shortly, then production this weekend if all goes well.
