### ISSUE TITLE
Feature request: better vertical alignment in new empty Board.

### ISSUE THREAD

**Issue by mcorossigo** [open-nomie/nomie#74]
Hello @brandoncorbin 
I'm sorry to not have come back at you for closing almost all my previous issue, but let me now say that you really did an incredible job on Nomie 4.4.0
It's just wonderful! Thank you!

Hoping to not bother you too much, I'm here with a new batch of issues/feauture request/suggestions.

Here, when I create a new Board there is this weid alignement of the +Tracker Button and "Sure is Empty!" string.

![IMG_3728](https://user-images.githubusercontent.com/36412793/68605715-254edc80-04ad-11ea-8721-baef483d1c65.PNG)

I would suggest you to vertically align them, with the string on the bottom.

For the screens and testing: Nomie Dev 4.4.8, iPhone 6S

**Comment by brandoncorbin** [comment]
Yep! this is a bug. It affects the search too... Good fine!
