### ISSUE TITLE
Consistent use of Board/Tab terminology

### ISSUE THREAD

**Issue by mcorossigo** [open-nomie/nomie#76]
In settings, there is "Show Board Tabs", in the home page when added or edited they are referred as "Tabs" but when edited whith "Edit Tab", the title says "Edit Board".

"Board" seems the right terminology to me, as it was used in Nomie 2.
In which case, "Show Board Tabs" should be replaced by "Show Board tabs" (tabs in lower case) as it refers to the UI element and not to an application component, and also every other "Tab" instance should be replaced.

Otherwise, "Edit Board" should be corrected

**Comment by brandoncorbin** [comment]
Board terminology is being deprecated, while It makes sense for existing Nomie users, its confusing for new ones;  while "tabs" are used in our every day life.  

I'll make things consistent.
