### ISSUE TITLE
Bug: tracker view vertically scrollable when not needed

### ISSUE THREAD

**Issue by mcorossigo** [open-nomie/nomie#78]
Even when the tab is empty, or have very few tracker, the pane is vertically scrollable by very little.

The screenshots are taken on iPhone 6S, the bug appear both in dark and light mode, 4.4.11 and 4.4.8, and with or without tabs enabled.
You can see the scroll bar differences.

|Scroll down| Scroll up|
|--|--|
|![IMG_3770](https://user-images.githubusercontent.com/36412793/68705885-27896780-058f-11ea-853b-0588055441d9.PNG)|![IMG_3769](https://user-images.githubusercontent.com/36412793/68705887-27896780-058f-11ea-9071-9014189cf82f.PNG)|

The bug does not seems to replicates on desktop.

**Comment by brandoncorbin** [comment]
Does it start off scrolled? Or, are you saying that the extract 20px of scroll at the bottom is  the bug? 

If it's not scrolled on start, then it won't be a big focus to fix, as getting the header / footer / content area to scroll properly is more important than some extra padding. 

Here's the problem - on iOS safari (not home screen) you have the toolbars. The toolbars only go away when scrolling the body.  So if you have an absolutely positioned header, footer and a main content area that overflows - the safari bars will not go away. 

To account for this, the Page component has a slot for header, footer and content. The header and footers are positioned fixed - and the content height is calculated and applied as a padding to the body content. Somewhere in that process some additional padding is being added.

**Comment by mcorossigo** [comment]
> Or, are you saying that the extract 20px of scroll at the bottom is the bug?

This. My point was that there should not be any scroll bars if there is not any content to scroll to, which is the case of this 20px empty padding.

On start, there is a jump just after the windows render which brings the page on the correct position (second screenshot).

Not a big deal, just a little quirk.

**Comment by brandoncorbin** [comment]
Think i found where the padding was being added. On smaller screens the bottom padding is greater than 25% of the view height... The board that holds the tracker was set to a min height of 75% of the view height... I've set that to 50 and it looks like the padding is gone. Will be pushing it this weekend.
