### ISSUE TITLE
Bug: Nomie 4.4.13 does not get past load screen

### ISSUE THREAD

**Issue by mcorossigo** [open-nomie/nomie#80]
After a reset, Nomie is blocked in a white screen right past the blue one with the version printed.

In Firefox it returns this errors:
```
> ⭐️ board.svelte ↠ The Log has changed! Let's see what trackers are in there log.js:34:1
> Added Trackers
> ✨    
Array []
log.js:34:1

> TypeError: o.activeBoard is null board.svelte:123:8
```

Tested also iPhones's Safari.

**Comment by brandoncorbin** [comment]
This was due to two bugs. One that didn't fully clear localstorage on reset, and one that didn't check if the activeBoard ID existed in the boards. This should be resolved after todays push.

**Comment by mcorossigo** [comment]
Can confirm that in 4.5 the bug is fixed 👍
