### ISSUE TITLE
Hide "Time" option in "Measure By" field of "Edit Tracker" menu

### ISSUE THREAD

**Issue by metamas** [open-nomie/nomie#88]
It took much tinkering for me to realize that the sole **Time** option under the **--Timer** section of the **Measure By** drop-down is never selectable. In the one case that it would seem to apply — when the tracker's **Type** is set to **Timer** — the **Measure By** field is hidden altogether.

Why not hide that section/option from the **Measure By** drop-down? Is there something I'm missing?

If this actually is a bug, I am happy to take it as a first opportunity to contribute.

_(visual reference for the points above)_

![image](https://user-images.githubusercontent.com/2520253/70005287-e0531e80-151d-11ea-8184-403dfa0711ed.png)

**Comment by brandoncorbin** [comment]
So sorry for completely missing this one - for what it's worth, this will be fixed in 5.6
